[build]
    publish = 'dist'
    command = 'pnpm run build'

[functions]    
    directory = 'functions'
    node_bundler = 'esbuild'
    external_node_modules = ['mongodb']
    
[[redirects]]
    from = '/*'
    to = 'index.html'
    status = 200

[dev]
    publish = 'src'
    command = 'pnpm start'
    port = 8080