[build]
    publish = "dist"
    command = "pnpm run build"

[dev]
    publish = "src"
    command = "pnpm start"
    port = 8080

[functions]
    directory = "functions"
    node_bundler = "esbuild"
    external_node_modules = ["mongodb"]

[[redirects]]
    from = "/*"
    to = "index.html"
    status = 200

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Headers = '*'