[build]
    publish = "dist"
    command = "pnpm run build"

[dev]
    publish = "src"
    command = "pnpm start"
    port = 8080

[functions]
    directory = "functions/"

[[redirects]]
    from = "/*"
    to = "index.html"
    status = 200

[[headers]]
    for = "/site.webmanifest"
    [headers.values]
        Content-Type = "application/manifest+json"

[[headers]]
    for = "/assets/*"
    [headers.values]
        cache-control = '''
        max-age=31536000,
        immutable
        '''