[build]
    publish = "dist"
    command = "pnpm run build"

[dev]
    publish = "src"
    command = "pnpm start"
    port = 8080

[functions]
    directory = "functions"
    node_bundler = "esbuild"

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Headers = '*'